// <auto-generated />
namespace Committes.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class maxlengthstudenttype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(maxlengthstudenttype));
        
        string IMigrationMetadata.Id
        {
            get { return "201610300201209_max-length-student-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
